Areas/Docente/Models/AdicionarProfessorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Capitulo01.Areas.Docente.Models
{
    public class AdicionarProfessorViewModel
    {
        public long? InstituicaoID { get; set; }
        public long? DepartamentoID { get; set; }
        public long? CursoID { get; set; }
        public long? ProfessorID { get; set; }
    }
}

Areas/Docente/Controllers/ProfessorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Capitulo01.Data;
using Capitulo01.Data.DAL.Cadastros;
using Modelo.Cadastros;
using Capitulo01.Data.DAL.Docente;
using Modelo.Docente;
using Capitulo01.Areas.Docente.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

namespace Capitulo01.Areas.Docente.Controllers
{
    [Area("Docente")]
    public class ProfessorController : Controller
    {
        private readonly IESContext _context;
        private readonly InstituicaoDAL instituicaoDAL;
        private readonly DepartamentoDAL departamentoDAL;
        private readonly CursoDAL cursoDAL;
        private readonly ProfessorDAL professorDAL;

        public ProfessorController(IESContext context)
        {
            _context = context;
            instituicaoDAL = new InstituicaoDAL(context);
            departamentoDAL = new DepartamentoDAL(context);
            cursoDAL = new CursoDAL(context);
            professorDAL = new ProfessorDAL(context);
        }

        public void PrepararViewBags(List<Instituicao> instituicoes, List<Departamento> departamentos, List<Curso> cursos, List<Professor> professores)
        {
            instituicoes.Insert(0, new Instituicao() { InstituicaoID = 0, Nome = "Selecione a instituição"});
            ViewBag.Instituicoes = instituicoes;

            departamentos.Insert(0, new Departamento() { DepartamentoID = 0, Nome = "Selecione o departamento" });
            ViewBag.Departamentos = departamentos;

            cursos.Insert(0, new Curso() { CursoID = 0, Nome = "Selecione o curso" });
            ViewBag.Cursos = cursos;


            professores.Insert(0, new Professor() { ProfessorID = 0, Nome = "Selecione o professor" });
            ViewBag.Professores = professores;
        }

        [HttpGet]
        public IActionResult AdicionarProfessor()
        {
            PrepararViewBags(instituicaoDAL.ObterInstituicoesClassificadasPorNome().ToList(), new List<Departamento>().ToList(), new List<Curso>().ToList(), new List<Professor>().ToList());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AdicionarProfessor([Bind("IntituicaoID, DepartamentoID, CursoID, ProfessorID")] AdicionarProfessorViewModel model)
        {
            if(model.InstituicaoID == 0 | model.DepartamentoID == 0 | model.CursoID == 0 | model.ProfessorID == 0)
            {
                ModelState.AddModelError("", "É preciso selecionar todos os dados.");
            }
            else
            {
                cursoDAL.RegistrarProfessor((long)model.CursoID, (long)model.ProfessorID);

                RegistrarProfessorNaSessao((long)model.CursoID, (long)model.ProfessorID);

                PrepararViewBags(instituicaoDAL.ObterInstituicoesClassificadasPorNome().ToList(), 
                    departamentoDAL.ObterDepartamentosPorInstituicao((long) model.InstituicaoID).ToList(), 
                    cursoDAL.ObterCursosPorDepartamento((long) model.DepartamentoID).ToList(), 
                    cursoDAL.ObterProfessoresForaDoCurso((long) model.CursoID).ToList());
            }
            return View(model);
        }

        public JsonResult ObterDepartamentosPorInstituicao(long actionID)
        {
            var departamentos = departamentoDAL.ObterDepartamentosPorInstituicao(actionID).ToList();
            return Json(new SelectList(departamentos, "DepartamentoID", "Nome"));
        }

        public JsonResult ObterCursosPorDepartamento(long actionID)
        {
            var cursos = cursoDAL.ObterCursosPorDepartamento(actionID).ToList();
            return Json(new SelectList(cursos, "CursoID", "Nome"));
        }

        public JsonResult ObterProfessoresForaDoCurso(long actionID)
        {
            var professores = cursoDAL.ObterProfessoresForaDoCurso(actionID).ToList();
            return Json(new SelectList(professores, "ProfessorID", "Nome"));
        }

        public void RegistrarProfessorNaSessao(long cursoID, long professorID)
        {
            var cursoProfessor = new CursoProfessor()
            {
                ProfessorID = professorID,
                CursoID = cursoID
            };
            List<CursoProfessor> cursosProfessor = new List<CursoProfessor>();
            string cursosProfessoresSession = HttpContext.Session.GetString("cursosProfessores");
            if (cursosProfessoresSession != null)
            {
                cursosProfessor = JsonConvert.DeserializeObject < List < CursoProfessor >> (cursosProfessoresSession);
            }
            cursosProfessor.Add(cursoProfessor);
            HttpContext.Session.SetString("cursosProfessores", JsonConvert.SerializeObject(cursosProfessor));
        }

        public IActionResult VerificarUltimosRegistros()
        {
            List<CursoProfessor> cursosProfessor = new List<CursoProfessor>();
            string cursosProfessoresSession = HttpContext.Session.GetString("cursosProfessores");
            if (cursosProfessoresSession != null)
            {
                cursosProfessor = JsonConvert.DeserializeObject < List < CursoProfessor >> (cursosProfessoresSession);
            }
            return View(cursosProfessor);
        }
    }
}

Areas/Docente/Views/Professor/AdicionarProfessor.cshtml
@model Capitulo01.Areas.Docente.Models.AdicionarProfessorViewModel

@{
    Layout = "_LayoutIES";
}

<div class="card-block">
    <div class="card-header	text-white	bg-danger	text-center	h1">
        Registrando um professor em um curso
    </div>
    <div class="card-body">
        <form asp-action="AdicionarProfessor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InstituicaoID" class="control-label"></label>
                <select asp-for="InstituicaoID" class="form-control" asp-items="@(new SelectList(@ViewBag.Instituicoes, "InstituicaoID", "Nome"))"></select>
            </div>
            <div class="form-group">
                <label asp-for="DepartamentoID" class="control-label"></label>
                <select asp-for="DepartamentoID" class="form-control"
                        asp-items="@(new SelectList(@ViewBag.Departamentos,	"DepartamentoID",	"Nome"))"
                        data-url="@Url.Action("ObterDepartamentosPorInstituicao", "Professor", new { area = "Docente" })">
                </select>
            </div>
            <div class="form-group">
                <label asp-for="CursoID" class="control-label"></label>
                <select asp-for="CursoID" class="form-control" asp-items="@(new	SelectList(@ViewBag.Cursos, "CursoID", "Nome"))"
                        data-url="@Url.Action("ObterCursosPorDepartamento", "Professor", new { area = "Docente" })">
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ProfessorID" class="control-label"></label>
                <select asp-for="ProfessorID" class="form-control" asp-items="@(new	SelectList(@ViewBag.Professores, "ProfessorID",	"Nome"))"
                        data-url="@Url.Action("ObterProfessoresForaDoCurso", "Professor", new { area = "Docente" })">
                </select>
            </div>
            <div class="form-group text-center	h3">
                <input type="submit" value="Registrar Professor" class="btn	btn-light" />
                <a asp-action="VerificarUltimosRegistros" class="btn btn-info">Verificar últimos registros</a>
            </div>
        </form>
    </div>
    <div class="card-footer bg-dark text-center text-white">
        Informe os	dados acima e/ou clique em um dos botões de ação
    </div>
</div>

@section ScriptPage	{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
        $(document).on("change", '#InstituicaoID', function (e) {
            var instituicaoID = $(this).find(":selected").val();
            GetDadosParaDropDownList(instituicaoID, '#DepartamentoID', 'DEPARTAMENTO');
        });
        $(document).on("change", '#DepartamentoID', function (e) {
            var departamentoID = $(this).find(":selected").val();
            GetDadosParaDropDownList(departamentoID, '#CursoID', 'CURSO');
        });
        $(document).on("change", '#CursoID', function (e) {
            var cursoID = $(this).find(":selected").val();
            GetDadosParaDropDownList(cursoID, '#ProfessorID', 'PROFESSOR');
        });
        function GetDadosParaDropDownList(valorBuscar, controleAtualizar, nomeDado) {
            var optionControleAtualizar = controleAtualizar + '	option';
            if (valorBuscar.length > 0) {
                var url = $(controleAtualizar).data('url');
                $.getJSON(url, { actionID: valorBuscar }, function (dadosRecebidos) {
                    $(optionControleAtualizar).remove();
                    $(controleAtualizar).append('<option value="0">Selecione o ' + nomeDado + '</option');
                    for (i = 0; i < dadosRecebidos.length; i++) {
                        $(controleAtualizar).append('<option value = "' + dadosRecebidos[i].value + '" > ' + dadosRecebidos[i].text + '</option');
                    }
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    debugger;
                    alert('Erro de conexão', 'Erro obtendo dados'
                    );
                });
            } else {
                $(optionControleAtualizar).remove();
                $(controleAtualizar).append('<option value=""></option');
            }
        }
    </script>
}

Areas/Docente/Views/Professor/VerificarUltimosRegistros.cshtml
@model IEnumerable<Modelo.Docente.CursoProfessor>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>VerificarUltimosRegistros</title>
</head>
<body>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Curso)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Professor)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CursoID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProfessorID)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p>
        <a asp-action="AdicionarProfessor">Voltar para Adicionar Professor</a>
    </p>

</body>
</html>